version: '3.4'

services:
  pxlschoolmanagement:
    image: ${DOCKER_REGISTRY-}pxlschoolmanagement
    ports:
       - "5000:5000"
    build:
      context: .
      dockerfile: PXLSchoolManagement/Dockerfile
    depends_on:
        - sqlserverdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000
      - DEBUG_MODE=Docker
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  sqlserverdb: 
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
    environment:
        SA_PASSWORD: "Sqlserver123"
        ACCEPT_EULA: "Y"
    
