version: '3.4'

services:
  pxlschoolmanagement:
    image: ${DOCKER_REGISTRY-}pxlschoolmanagement
    ports:
       - "5000:5000"
    build:
      context: .
      dockerfile: PXLSchoolManagement/Dockerfile
    depends_on:
        - sqlserverdb
  sqlserverdb: 
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
    environment:
        SA_PASSWORD: "Sqlserver123"
        ACCEPT_EULA: "Y"
    
